version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: php_docker_user
      MYSQL_PASSWORD: 3e@r3!
      MYSQL_ROOT_PASSWORD: root#3e@r3!
      MYSQL_DATABASE: php_docker
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    networks:
      - app-network
    links:
      - db
    volumes:
      - ./src:/var/www/app
    ports:
      - "9000:9000"
    container_name: php-app
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    networks:
      - app-network
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./src:/var/www/app
    links:
      - php

networks:
  app-network:
    driver: bridge
